
import { ArrowLeft, Download, Info } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { useToast } from "@/components/ui/use-toast";
import { generateAnalysisPDF } from "@/utils/pdfGenerator";
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from "@/components/ui/tooltip";

interface AIAnalysisDisplayProps {
  symbol: string;
  type: 'technical' | 'sentiment' | 'prediction' | 'crypto' | 'stock';
  analysisResult: string;
  loading: boolean;
  onBack: () => void;
}

export function AIAnalysisDisplay({ 
  symbol, 
  type,
  analysisResult, 
  loading, 
  onBack 
}: AIAnalysisDisplayProps) {
  const { toast } = useToast();

  const formatAnalysisText = (text: string) => {
    return text.split('**').map((part, index) => 
      index % 2 === 1 ? <strong key={index} className="font-bold">{part}</strong> : part
    );
  };

  const downloadPDF = () => {
    try {
      const pdf = generateAnalysisPDF(symbol, analysisResult);
      pdf.save(`${symbol}_analysis.pdf`);

      toast({
        title: "Success",
        description: "Analysis report downloaded successfully",
      });
    } catch (error) {
      console.error("Error generating PDF:", error);
      toast({
        title: "Error",
        description: "Failed to generate PDF. Please try again.",
        variant: "destructive",
      });
    }
  };

  return (
    <div className="space-y-4 w-full max-w-7xl px-4">
      <Button variant="outline" onClick={onBack} className="mb-4">
        <ArrowLeft className="h-4 w-4 mr-2" />
        Back
      </Button>
      <div className="p-6 rounded-lg border bg-muted/50">
        <h3 className="font-semibold mb-4 text-xl">Analysis for {symbol}</h3>
        {loading ? (
          <div className="flex flex-col items-center justify-center py-16">
            <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary mb-4"></div>
            <p className="text-muted-foreground">Analyzing {symbol}...</p>
            <p className="text-xs text-muted-foreground mt-2">This might take a few moments</p>
          </div>
        ) : (
          <>
            <div className="whitespace-pre-wrap break-words mb-6 text-lg leading-relaxed">
              {formatAnalysisText(analysisResult)}
            </div>
            <Alert className="mb-6">
              <div className="flex items-start gap-2">
                <Info className="h-4 w-4 mt-0.5 flex-shrink-0" />
                <AlertDescription>
                  Disclaimer: This analysis is generated by AI and may contain errors or inaccuracies. 
                  Please use this information as one of many data points in your research process.
                </AlertDescription>
              </div>
            </Alert>
            <TooltipProvider>
              <Tooltip>
                <TooltipTrigger asChild>
                  <Button 
                    onClick={downloadPDF}
                    className="w-full gap-2 neo-brutal-shadow hover:bg-primary/10 hover:text-foreground hover:border-primary/50 transition-colors duration-300"
                    variant="outline"
                  >
                    <Download className="h-4 w-4" />
                    Download Analysis as PDF
                  </Button>
                </TooltipTrigger>
                <TooltipContent>
                  <p>Save this analysis as a PDF document</p>
                </TooltipContent>
              </Tooltip>
            </TooltipProvider>
          </>
        )}
      </div>
    </div>
  );
}
